version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
#    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    rules:
      - text: "Error return value of .* is not checked"
        linters:
          - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
