name: config-kueue
tasks:
- id: register-cluster-queue
  type: RegisterObj
  params:
    template: "resources/templates/kueue/cluster-queue.yml"
- id: register-local-queue
  type: RegisterObj
  params:
    template: "resources/templates/kueue/local-queue.yml"
- id: register-resource-flavor
  type: RegisterObj
  params:
    template: "resources/templates/kueue/resource-flavor.yml"
- id: register
  type: RegisterObj
  params:
    template: "resources/benchmarks/templates/kueue/job.yml"
    nameFormat: "job{{._ENUM_}}"
    podNameFormat: "{{._NAME_}}-[0-9]-.*"
    podCount: "{{.replicas}}"
- id: create-resource-flavor
  type: SubmitObj
  params:
    refTaskId: register-resource-flavor
    canExist: true
    params:
      name: "gpu-node"
      nodeLabels:
        nvidia.com/gpu.count: "8"
- id: create-cluster-queue
  type: SubmitObj
  params:
    refTaskId: register-cluster-queue
    canExist: true
    params:
      name: team
      flavor: gpu-node
      cpu: 50
      memory: 360Gi
      pods: 500
      gpu: 4000
- id: create-local-queue
  type: SubmitObj
  params:
    refTaskId: register-local-queue
    canExist: true
    params:
      name: team-queue
      namespace: default
      clusterQueue: team
- id: configure
  type: Configure
  params:
    configmaps:
    - name: kueue-manager-config
      namespace: kueue-system
      op: create
      data:
        controller_manager_config.yaml: |
          apiVersion: config.kueue.x-k8s.io/v1beta1
          kind: Configuration
          health:
            healthProbeBindAddress: :8081
          metrics:
            bindAddress: :8080
          # enableClusterQueueResources: true
          webhook:
            port: 9443
          leaderElection:
            leaderElect: true
            resourceName: c1f6bfd2.kueue.x-k8s.io
          controller:
            groupKindConcurrency:
              Job.batch: 5
              Pod: 5
              Workload.kueue.x-k8s.io: 5
              LocalQueue.kueue.x-k8s.io: 1
              ClusterQueue.kueue.x-k8s.io: 1
              ResourceFlavor.kueue.x-k8s.io: 1
          clientConnection:
            qps: 50
            burst: 100
          #pprofBindAddress: :8083
          waitForPodsReady:
            enable: true
            timeout: 5m
            blockAdmission: true
            requeuingStrategy:
              timestamp: Eviction
              backoffLimitCount: null # null indicates infinite requeuing
              backoffBaseSeconds: 60
              backoffMaxSeconds: 3600
          #manageJobsWithoutQueueName: true
          #internalCertManagement:
          #  enable: false
          #  webhookServiceName: ""
          #  webhookSecretName: ""
          integrations:
            frameworks:
            - "batch/job"
            - "kubeflow.org/mpijob"
            - "ray.io/rayjob"
            - "ray.io/raycluster"
            - "jobset.x-k8s.io/jobset"
            - "kubeflow.org/mxjob"
            - "kubeflow.org/paddlejob"
            - "kubeflow.org/pytorchjob"
            - "kubeflow.org/tfjob"
            - "kubeflow.org/xgboostjob"
          #  - "pod"
          #  externalFrameworks:
          #  - "Foo.v1.example.com"
          #  podOptions:
          #    namespaceSelector:
          #      matchExpressions:
          #        - key: kubernetes.io/metadata.name
          #          operator: NotIn
          #          values: [ kube-system, kueue-system ]
          #fairSharing:
          #  enable: true
          #  preemptionStrategies: [LessThanOrEqualToFinalShare, LessThanInitialShare]
          #resources:
          #  excludeResourcePrefixes: []
    deploymentRestarts:
    - namespace: kueue-system
      name: kueue-controller-manager
    timeout: 1m
