name: config-runai
description: register, deploy and configure run:ai custom resources
tasks:
- id: register-trainingworkload
  type: RegisterObj
  params:
    template: "resources/benchmarks/templates/runai/trainingworkload.yaml"
    nameFormat: "twl{{._ENUM_}}"
    podNameFormat: "{{._NAME_}}-0-0"
    podCount: 1
- id: register-mpi
  type: RegisterObj
  params:
    template: "resources/benchmarks/templates/runai/mpijob.yaml"
    nameFormat: "mpijob{{._ENUM_}}"
    podNameFormat: "{{._NAME_}}-(launcher-[a-z0-9]+|worker-[0-9]+)"
    podCount: "{{.workers}} + 1"
