name: config-nodes
description: create 500 virtual GPU nodes
tasks:
- id: configure
  type: Configure
  params:
    nodes:
    - type: dgxa100.80g
      count: 500
      labels:
        nvidia.com/gpu.count: "8"
    timeout: 5m
