name: config-nodes
description: |
  This test is designed to run on a cluster of 32 GPU nodes (8 GPUs per node).
tasks:
- id: configure
  type: Configure
  params:
    nodes:
    - type: dgxa100.80g
      count: 32
      labels:
        nvidia.com/gpu.count: "8"
    timeout: 1m
