apiVersion: batch/v1
kind: Job
metadata:
  name: "{{._NAME_}}"
  namespace: "default"
spec:
  completions: {{.replicas}}
  parallelism: {{.replicas}}
  template:
    metadata:
      labels:
        runai/queue: "test"
      annotations:
        pod-complete.stage.kwok.x-k8s.io/delay: {{.ttl}}
        pod-complete.stage.kwok.x-k8s.io/jitter-delay: {{.ttl}}
    spec:
      schedulerName: kai-scheduler
      containers:
      - name: test
        image: busybox
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 250M
            nvidia.com/gpu: "8"
          requests:
            cpu: 100m
            memory: 250M
            nvidia.com/gpu: "8"
      restartPolicy: Never
