apiVersion: scheduling.run.ai/v2
kind: Queue
metadata:
  name: "{{.name}}"
spec:
  {{- if .parentQueue }}
  parentQueue: "{{.parentQueue}}"
  {{- end }}
  resources:
    cpu:
      quota: -1
      limit: -1
      overQuotaWeight: 1
    gpu:
      quota: -1
      limit: -1
      overQuotaWeight: 1
    memory:
      quota: -1
      limit: -1
      overQuotaWeight: 1
