{
 "title": "Kubernetes Pods Scheduling metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})",
     "legendFormat": "Pods pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})",
     "legendFormat": "Pods running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})",
     "legendFormat": "Pods succeeded"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})",
     "legendFormat": "Pods failed"
    }
   ]
  },
  {
   "title": "CPU requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node!=\"kind-control-plane\", resource=\"cpu\"})",
     "legendFormat": "CPU limits"
    },
    {
     "expr": "namespace_cpu:kube_pod_container_resource_requests:sum{namespace=~\"$namespace\"}",
     "legendFormat": "CPU requests"
    }
   ]
  },
  {
   "title": "Memory requests (GiB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{node!=\"kind-control-plane\", resource=\"memory\"})/(1000000000*1.073741824)",
     "legendFormat": "Memory limit"
    },
    {
     "expr": "namespace_memory:kube_pod_container_resource_requests:sum{namespace=~\"$namespace\"}/(1000000000*1.073741824)",
     "legendFormat": "Memory requests"
    }
   ]
  },
  {
   "title": "CPU utilisation (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "\r\n(sum (  cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{resource=\"cpu\"}   * on (pod) group_left    kube_pod_status_phase{namespace=\"default\", phase=\"Running\"} ) / sum(kube_node_status_allocatable{node!=\"kind-control-plane\", resource=\"cpu\"}))*100",
     "legendFormat": "CPU cluster utilization"
    }
   ]
  },
  {
   "title": "Memory utilisation (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "(sum (\r\n  cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{resource=\"memory\"}\r\n  * on (pod) group_left \r\n  kube_pod_status_phase{namespace=\"default\", phase=\"Running\"}\r\n) / sum(kube_node_status_allocatable{node!=\"kind-control-plane\", resource=\"memory\"}))*100",
     "legendFormat": "Memory limit"
    }
   ]
  },
  {
   "title": "Average CPU utilisation (%) over period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum (  cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests{resource=\"cpu\"}   * on (pod) group_left    kube_pod_status_phase{namespace=\"default\", phase=\"Running\"} ) / sum(kube_node_status_allocatable{node!=\"kind-control-plane\", resource=\"cpu\"}))*100",
     "legendFormat": "CPU cluster utilization"
    }
   ]
  },
  {
   "title": "Average memory utilisation (%) over period",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum (\r\n  cluster:namespace:pod_memory:active:kube_pod_container_resource_requests{resource=\"memory\"}\r\n  * on (pod) group_left \r\n  kube_pod_status_phase{namespace=\"default\", phase=\"Running\"}\r\n) / sum(kube_node_status_allocatable{node!=\"kind-control-plane\", resource=\"memory\"}))*100",
     "legendFormat": "Memory limit"
    }
   ]
  },
  {
   "title": "Pods distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum (kube_pod_container_status_running\r\n  * on(pod, pod) group_left(node)\r\n  node_namespace_pod:kube_pod_info:{namespace=~\"$namespace\", node!~\"kind-control-plane\"}\r\n  ) by (node)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_container_status_running{namespace=~\"$namespace\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  kube_pod_container_status_ready{namespace=~\"$namespace\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  kube_pod_container_status_terminated{namespace=~\"$namespace\"}\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  kube_pod_container_status_waiting{namespace=~\"$namespace\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_container_status_waiting{namespace=~\"$namespace\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods ready",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_container_status_ready{namespace=~\"$namespace\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods running",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_container_status_running{namespace=~\"$namespace\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods terminated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "sum(\r\n  kube_pod_container_status_terminated{namespace=~\"$namespace\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}