name: test-k8s-job
description: submit and validate a k8s job
tasks:
- id: register
  type: RegisterObj
  params:
    template: "resources/templates/k8s/failed-job.yml"
    nameFormat: "job{{._ENUM_}}"
    podNameFormat: "{{._NAME_}}-[0-9]-.*"
    podCount: "{{.parallelism}}"
- id: configure
  type: Configure
  params:
    nodes:
    - type: dgxa100.80g
      count: 2
      labels:
        nvidia.com/gpu.count: "8"
    timeout: 1m
- id: job
  type: SubmitObj
  params:
    refTaskId: register
    count: 1
    params:
      namespace: default
      parallelism: 1
      completions: 1
      backoffLimit: 0
      completionMode: NonIndexed
      image: ubuntu
      cpu: 100m
      memory: 512M
      gpu: 8
      containerImage: ubuntu
      initContainerImage: nccl
      failureContainerName: nccl-test
      failureReason: nccl-test-failed
      failureMessage: "nccl test failed"
      failureExitCode: 1
      failureDelay: 1000
      failureJitterDelay: 5000
- id: status
  type: CheckPod
  params:
    refTaskId: job
    status: Failed
    timeout: 10s
