apiVersion: run.ai/v2alpha1
kind: TrainingWorkload
metadata:
  name: "{{._NAME_}}"
  namespace: runai-<RUNAI_PROJECT>
  annotations:
    clusterId: <RUNAI_CLUSTER_ID>
  labels:
    project: <RUNAI_PROJECT>
spec:
  name:
    value: "{{._NAME_}}"
  image:
    value: ubuntu
  imagePullPolicy:
    value: IfNotPresent
  active:
    value: true
  annotations:
    items:
      clusterId:
        value: <RUNAI_CLUSTER_ID>
      pod-complete.stage.kwok.x-k8s.io/delay:
        value: {{.ttl}}
      pod-complete.stage.kwok.x-k8s.io/jitter-delay:
        value: {{.ttl}}
  cpu:
    value: 100m
  memory:
    value: 256M
  gpuDevices:
    value: 8
  nodePools:
    value: default
  usage: Submit
