apiVersion: v1
kind: ServiceAccount
metadata:
  name: knavigator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: knavigator
subjects:
- kind: ServiceAccount
  name: knavigator
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
