apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node-resource-exporter.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: [get,list,watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node-resource-exporter.serviceAccountName" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "node-resource-exporter.serviceAccountName" . }}
  namespace: {{.Release.Namespace}}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: {{ include "node-resource-exporter.serviceAccountName" . }}
  apiGroup: ""
