# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: "05 07 * * *" # Everyday 07:05 AM UTC

jobs:
  test-volcano:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make build

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1

    - name: Run test scripts
      run: |
        ./tests/ci/test_volcano.sh

  test-jobset:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make build

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1

    - name: Run test scripts
      run: |
        ./tests/ci/test_jobset.sh

  test-kueue:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make build

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1

    - name: Run test scripts
      run: |
        ./tests/ci/test_kueue.sh

  test-yunikorn:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: make build

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1

    - name: Run test scripts
      run: |
        ./tests/ci/test_yunikorn.sh
